In [109]:
# Student ID : C0859752
# Name: Kavya Nagesh
# Assigning the variable sampltxt with the sentence
sampltxt = "         Jack and jill have made a delicious,       dish. Then they started to play some12 game! and jill attached the # [a] photo frame to the straight9 wall and swung on a sea-saw. She was very happy. After the game, they both went to central London to enjoy some fast food."
sampltxt

'         Jack and jill have made a delicious,       dish. Then they started to play some12 game! and jill attached the # [a] photo frame to the straight9 wall and swung on a sea-saw. She was very happy. After the game, they both went to central London to enjoy some fast food.'

In [40]:
# 1. Remove punctuation
# Importing regex package to use split methods
import re
#sampl_punct = re.split("\s+", sampltxt)
sampl_punct = re.split("\W+", sampltxt)
#sampl_punct

# Importing string package to use punctuation methods
import string
string.punctuation

# remove all the punctuations from the given text string by passing the text to a custom defined method - remove_punct
# remove_punct loops within each character to scan for any punctuation marks and returns that are not matching with the punctuation list from string package
def remove_punct(sampltxt):
    text_nonpunct = [char for char in sampltxt if char not in string.punctuation]
    return text_nonpunct

sampl_punct1 = remove_punct(sampl_punct)
sampl_punct2 = ' '.join(sampl_punct1)
sampl_punct2

'Jack and jill have made a delicious dish Then they started to play some12 game and jill attached the a photo frame to the straight9 wall and swung on a sea saw She was very happy After the game they both went to central London to enjoy some fast food'

In [41]:
# 2. Tokenize Sentence
# Importing Tokenize package and sub packages - word and sent tokenize
from nltk.tokenize import word_tokenize, sent_tokenize

# sent_tokenize method for the entire sentence 
sampl_sents = sent_tokenize(sampl_punct2)
sampl_sents

['Jack and jill have made a delicious dish Then they started to play some12 game and jill attached the a photo frame to the straight9 wall and swung on a sea saw She was very happy After the game they both went to central London to enjoy some fast food']

In [48]:
# 3. Tokenize word 
# word_tokenize method for all the words in the sentence
sampl_words = [word_tokenize(sent) for sent in sampl_sents]
sampl_words

[['Jack',
  'and',
  'jill',
  'have',
  'made',
  'a',
  'delicious',
  'dish',
  'Then',
  'they',
  'started',
  'to',
  'play',
  'some12',
  'game',
  'and',
  'jill',
  'attached',
  'the',
  'a',
  'photo',
  'frame',
  'to',
  'the',
  'straight9',
  'wall',
  'and',
  'swung',
  'on',
  'a',
  'sea',
  'saw',
  'She',
  'was',
  'very',
  'happy',
  'After',
  'the',
  'game',
  'they',
  'both',
  'went',
  'to',
  'central',
  'London',
  'to',
  'enjoy',
  'some',
  'fast',
  'food']]

In [51]:
# 4. Remove stopwords
# Importing corpus package from nltk package to get the list of all stopwords
from nltk.corpus import stopwords
from string import punctuation

# Creating a custom stopwrods variable to make it hold all the English language stopwords and Punctuation 
# marks appended to make a single variable
customStopWords = set(stopwords.words('english')+list(punctuation))

sampl_nostopwords = [word for word in word_tokenize(sampl_punct2) if word not in customStopWords]
sampl_nostopwords

# Converting the List data type (sampl_nostopwords) to String Data Type
sampl_nostopwords1 = ' '.join(sampl_nostopwords)
sampl_nostopwords1

'Jack jill made delicious dish Then started play some12 game jill attached photo frame straight9 wall swung sea saw She happy After game went central London enjoy fast food'

In [57]:
# 5. Stem 
# Using the Stemming method from nltk to stem the words in our data
import nltk
ps = nltk.PorterStemmer()
sampl_stem = ps.stem(sampl_nostopwords1)
sampl_stem

'jack jill made delicious dish then started play some12 game jill attached photo frame straight9 wall swung sea saw she happy after game went central london enjoy fast food'

In [61]:
# 6. Lemmatize
# Using the Lemmatozing method from nltk to stem the words in our data
wn = nltk.WordNetLemmatizer()
sampl_lemm = wn.lemmatize(sampl_nostopwords1)
sampl_lemm

# Converting the String to List datatype in order to use it on Vectorization
sampl_lstlemm = list(sampl_lemm.split(" "))
sampl_lstlemm

['Jack',
 'jill',
 'made',
 'delicious',
 'dish',
 'Then',
 'started',
 'play',
 'some12',
 'game',
 'jill',
 'attached',
 'photo',
 'frame',
 'straight9',
 'wall',
 'swung',
 'sea',
 'saw',
 'She',
 'happy',
 'After',
 'game',
 'went',
 'central',
 'London',
 'enjoy',
 'fast',
 'food']

In [71]:
# 7. Count vectorization
#import CountVectorizer from sklearn.feature_extracation.text
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Initializing the CountVectorizer method in a variable
vectorizer = CountVectorizer()

# Fitting the data we have into the instance of CountVectorizer
X_vect = vectorizer.fit(sampl_lstlemm)
X_samp = vectorizer.fit_transform(sampl_lstlemm)

# Using shape method we can see the number of rows and cols of our Sample data
X_samp.shape

# To get a list of Feature names of our data
vectorizer.get_feature_names()

X_counts_df = pd.DataFrame(X_samp.toarray())
X_counts_df

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [87]:
# 8. n-grams
# a) n-gram range (2,2)
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
n_gram_vect = CountVectorizer(ngram_range=(2,2))

# Converting the data into a dictionary of 2 items since our data only has one row
sampl_dictlemm = (sampl_lemm,)
X_samp1 = n_gram_vect.fit_transform(sampl_dictlemm)
X_samp1.shape
n_gram_vect.get_feature_names()

X_counts_df1 = pd.DataFrame(X_samp1.toarray())
X_counts_df1

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [93]:
# b) n-gram range (2,3)
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
n_gram_vect1 = CountVectorizer(ngram_range=(2,3))

# Same approach used as above to apply it on n-grm range for (2,3)
sampl_dictlemm1 = (sampl_lemm,)
X_samp2 = n_gram_vect1.fit_transform(sampl_dictlemm1)
X_samp2.shape
n_gram_vect1.get_feature_names_out()

X_counts_df2 = pd.DataFrame(X_samp2.toarray())
X_counts_df2

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [110]:
# 9. TF-IDF 
from sklearn.feature_extraction.text import TfidfVectorizer

# Same approach followed below
tfidf_vect = TfidfVectorizer()
X_tfidf = tfidf_vect.fit_transform(sampl_dictlemm1)
X_tfidf.shape
tfidf_vect.get_feature_names()

X_tfidf_df = pd.DataFrame(X_tfidf.toarray())
X_tfidf_df

X_tfidf_df.columns = tfidf_vect.get_feature_names()
X_tfidf_df

C:\Users\Kavya\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,after,attached,central,delicious,dish,enjoy,fast,food,frame,game,...,saw,sea,she,some12,started,straight9,swung,then,wall,went
0,0.174078,0.174078,0.174078,0.174078,0.174078,0.174078,0.174078,0.174078,0.174078,0.348155,...,0.174078,0.174078,0.174078,0.174078,0.174078,0.174078,0.174078,0.174078,0.174078,0.174078